import json
import os
from typing import Dict, Optional, Tuple

from openai import OpenAI


def _load_prompt() -> str:
    base_dir = os.path.dirname(__file__)
    prompt_path = os.path.join(base_dir, "prompt_conduct_learning.txt")
    with open(prompt_path, "r", encoding="utf-8") as f:
        return f.read()


def _build_subject_avg_text(subject_avgs: Dict[str, float]) -> str:
    if not subject_avgs:
        return ""
    items = sorted(subject_avgs.items(), key=lambda kv: kv[1], reverse=True)
    return ", ".join([f"{k}: {v:.2f}" for k, v in items])


def evaluate_conduct_and_learning_with_ai(
    *,
    student_name: str,
    positive_count: int,
    reminder_count: int,
    subject_averages: Dict[str, float],
    overall_average: Optional[float],
) -> Tuple[str, str]:
    """
    Return (conduct_comment, learning_comment) generated by GPT.
    Always attempts to parse strict JSON from AI. Raises on unexpected responses.
    """
    api_key = os.getenv("OPENAI_API_KEY", "")
    prompt = _load_prompt()
    subject_avg_text = _build_subject_avg_text(subject_averages)
    overall_avg_text = f"{overall_average:.2f}" if overall_average is not None else ""

    filled = (
        prompt
        + "\n\n--- Dữ liệu ---\n"
        + f"Họ tên học sinh: {student_name}\n"
        + f"Số lần cộng điểm: {positive_count}\n"
        + f"Số lần nhắc nhở: {reminder_count}\n"
        + f"Điểm trung bình toàn môn (nếu có): {overall_avg_text}\n"
        + f"Điểm trung bình theo môn: {subject_avg_text}\n"
    )

    if not api_key:
        raise RuntimeError("OPENAI_API_KEY is missing")

    client = OpenAI(api_key=api_key)
    resp = client.responses.create(
        model="gpt-4.1-mini",
        input=filled,
        temperature=0.2,
    )
    content = (resp.output_text or "").strip()
    data = json.loads(content)
    return data["conduct_comment"], data["learning_comment"]

